<template>
  <div class="system-settings">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ $t('settings.systemLanguage') }}</span>
        </div>
      </template>
      
      <el-form label-width="120px">
        <el-form-item :label="$t('settings.currentLanguage')">
          <el-radio-group 
            v-model="currentLanguage" 
            @change="handleLanguageChange"
            :disabled="loading"
          >
            <el-radio label="zh">简体中文</el-radio>
            <el-radio label="en">English</el-radio>
          </el-radio-group>
          <div v-if="loading" style="margin-top: 8px; color: var(--el-color-primary);">
            <el-icon class="is-loading"><Loading /></el-icon>
            {{ currentLanguage === 'zh' ? '正在切换语言...' : 'Switching language...' }}
          </div>
        </el-form-item>
        
        <el-form-item>
          <el-alert
            :title="$t('settings.languageSwitchNotice')"
            type="warning"
            :closable="false"
            show-icon
          >
            <template #default>
              <p>{{ $t('settings.languageSwitchDesc') }}</p>
              <ul>
                <li>{{ $t('settings.languageSwitchItem1') }}</li>
                <li>{{ $t('settings.languageSwitchItem2') }}</li>
                <li>{{ $t('settings.languageSwitchItem3') }}</li>
              </ul>
            </template>
          </el-alert>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Loading } from '@element-plus/icons-vue'
import { settingsAPI } from '@/api/settings'
import { useI18n } from 'vue-i18n'

const { locale } = useI18n()
const currentLanguage = ref<'zh' | 'en'>('zh')
const loading = ref(false)

const loadCurrentLanguage = async () => {
  try {
    const res = await settingsAPI.getLanguage()
    currentLanguage.value = res?.language as 'zh' | 'en'
    // 同步前端语言
    locale.value = res?.language as 'zh' | 'en'
    console.log('Current language loaded:', res?.language)
  } catch (error) {
    console.error('Failed to load language:', error)
    const errorMsg = currentLanguage.value === 'zh' 
      ? '获取语言设置失败' 
      : 'Failed to load language settings'
    ElMessage.error(errorMsg)
  }
}

const handleLanguageChange = async (value: 'zh' | 'en') => {
  // 双语确认消息
  const confirmMessage = value === 'zh' 
    ? `切换为中文后，后端生成的所有提示词、角色描述、场景描述等都将使用中文。是否继续？


After switching to Chinese, all prompts, character descriptions, scene descriptions generated by the backend will use Chinese. Continue?`
    : `After switching to English, all prompts, character descriptions, scene descriptions generated by the backend will use English. Continue?


切换为英文后，后端生成的所有提示词、角色描述、场景描述等都将使用英文。是否继续？`
  
  try {
    await ElMessageBox.confirm(
      confirmMessage,
      '切换语言 / Switch Language',
      {
        confirmButtonText: '确定 / Confirm',
        cancelButtonText: '取消 / Cancel',
        type: 'warning',
        dangerouslyUseHTMLString: false
      }
    )

    loading.value = true
    console.log('Updating language to:', value)
    
    const res = await settingsAPI.updateLanguage(value)
    console.log('Language update response:', res)
    
    // 同时更新前端语言
    locale.value = value
    
    // 使用后端返回的双语消息（request拦截器已经返回了data）
    ElMessage.success({
      message: res?.message || (value === 'zh' ? '语言已切换为中文' : 'Language switched to English'),
      duration: 3000
    })
  } catch (error: any) {
    console.error('Language update error:', error)
    
    if (error !== 'cancel') {
      // 安全获取错误消息
      let errorMessage = '未知错误'
      if (error?.message) {
        errorMessage = error.message
      } else if (error?.response?.data?.error?.message) {
        errorMessage = error.response.data.error.message
      } else if (typeof error === 'string') {
        errorMessage = error
      }
      
      // 双语错误提示
      const errorMsg = currentLanguage.value === 'zh'
        ? `切换语言失败: ${errorMessage}`
        : `Failed to switch language: ${errorMessage}`
      
      ElMessage.error({
        message: errorMsg,
        duration: 5000
      })
    }
    
    // 恢复原来的选择
    await loadCurrentLanguage()
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadCurrentLanguage()
})
</script>

<style scoped>
.system-settings {
  padding: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

:deep(.el-alert ul) {
  margin-top: 10px;
  padding-left: 20px;
}

:deep(.el-alert li) {
  margin: 5px 0;
}
</style>
